### ISSUE TITLE
People proposal

### ISSUE THREAD

**Issue by effigies** [poldracklab/poldracklab.github.io#3]
We could write people in a YAML file:

```YAML
---
- PI:
  - name: Russ Poldrack
    website: https://poldrack.github.io
    twitter: poldrack
    ...
- Research Scientists:
  - name: Patrick Bissett
  - name: Joshua Buckholtz
  - name: Jeanette Mumford
...
```

I suspect we could then use [Listing templates](https://quarto.org/docs/websites/website-listings-custom.html#listing-templates) to do generate the listings we currently have. Links like Twitter/GitHub/ORCID could be done by appending icons. Quarto has [extensions](https://quarto.org/docs/extensions/index.html) that would make that fairly easy.
